Repository TopAcademy2022/checkers, pull requests merged in 2024-09, with the labels that each got.

#2 Added project files. Closed #1
  Checkers.sln
  Checkers/App.xaml
  Checkers/App.xaml.cs
  Checkers/Checkers.csproj
  Checkers/MainWindow.xaml
  Checkers/MainWindow.xaml.cs
Labels: enhancement, good first issue

#12 Added figure placement. Closed #6
  Checkers/GridGame.cs
  Checkers/MainWindow.xaml
  Checkers/MainWindow.xaml.cs
Labels: enhancement

#13 Added testing. Closed #5
  Checkers.sln
  CheckersTests/CheckersTests.csproj
  CheckersTests/Tests.cs
Labels: enhancement, testing

#18 Added display for game figure. Closed #7
  Checkers/Graphics/GraphicalGameFigure.cs
Labels: enhancement

#25 Added Doxygen. Closed #4
  .gitignore
  Docs/Doxyfile
Labels: documentation

#27 Added logical game figure. Closed #17
  Checkers/App.xaml
  Checkers/Checkers.csproj
  Checkers/Graphics/GraphicalGameField.cs
  Checkers/Graphics/MainWindow.xaml
  Checkers/Logic/CheckersInterface.cs
  Checkers/Logic/GameField.cs
  Checkers/Logic/GameFigure.cs
  Checkers/Logic/Interfaces/ICheckersInterface.cs
Labels: enhancement

#26 Added rerender game field. Closed #24
  Checkers/Graphics/GraphicalGameField.cs
Labels: enhancement
