Repository TopAcademy2022/checkers, pull requests merged in 2024-10, with the labels that each got.

#34 Added implement the GetRightDiagonal method. Closed #29
  Checkers/Logic/GameField.cs
  Checkers/Logic/GameFigure.cs
Labels: documentation, enhancement

#36 Added database connection. Closed #31
  Checkers/Checkers.csproj
  Checkers/Logic/DatabaseConnection.cs
Labels: enhancement

#37 Added victory check in game. Closed #10
  Checkers/Logic/GameField.cs
Labels: documentation, enhancement

#39 Added class for figure posible movement. Closed #32
  Checkers/Graphics/GraficalFigurePosibleMovement.cs
Labels: enhancement

#42 Fixed empty cells field. Closed #41
  Checkers/Logic/GameField.cs
Labels: bug

#40 Add possible figure movement. Closed #20
  Checkers/Logic/GameField.cs
Labels: documentation, enhancement

#47 Added display possible figure movement. Closed #21
  Checkers/Graphics/GraphicalGameField.cs
  Checkers/Logic/CheckersInterface.cs
  Checkers/Logic/Interfaces/ICheckersInterface.cs
Labels: documentation, enhancement

#51 Added move figure method. Closed #23
  Checkers/Logic/GameField.cs
Labels: documentation, enhancement

#52 Added documentation for MoveFigureToCell method. Closed #43
  Checkers/Logic/GameField.cs
Labels: documentation

#54 Added test for GameField constructor. Closed #44
  Checkers/Logic/CheckersInterface.cs
  Checkers/Logic/GameField.cs
  Tests/Checkers.Tests/GameFieldTests.cs
Labels: documentation, enhancement, testing
